config/routes.rb
Rails.application.routes.draw do
  post "txt", to: 'txt#set'
  delete 'txt', to: 'txt#destroy'
  resources :domains
  root to: 'application#empty'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/domain.rb
class Domain < ApplicationRecord
  has_many :records, dependent: :delete_all
  self.inheritance_column = nil

  after_create :create_soa_record

  def create_soa_record
    Record.create!(domain: self, name: name, type: 'SOA', ttl: 300, content: soa_content)
  end

  def master_ns
    'dns1.domain.tld'
  end

  def hostmaster
    'hostmaster@domain.tld'
  end

  def initial_version
    Time.now.strftime('%Y%m%d')+'00'
  end

  def soa_timers
     '3600 900 1814400 7200'
  end

  def soa_content
    [master_ns, hostmaster, initial_version, soa_timers].join(' ')
  end
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :domain
  self.inheritance_column = nil

  after_save :bump_soa_version

  def bump_soa_version
    return if type == 'SOA'
    soa_record = domain.records.find_by(type: 'SOA')
    parts = soa_record.content.split(' ')
    date = parts[2][0..7]
    if Date.parse(date) < Date.today
       parts[2] = Time.now.localtime.strftime('%Y%m%d00')
    else
       parts[2] = (parts[2].to_i + 1).to_s
    end
    soa_record.update(content: parts.join(' '))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  http_basic_authenticate_with name: Rails.application.secrets.login,
                               password: Rails.application.secrets.password

  def empty
    render plain: ''
  end
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :set_domain, only: [:show, :edit, :update, :destroy]

  # GET /domains
  # GET /domains.json
  def index
    @domains = Domain.all
  end

  # GET /domains/1
  # GET /domains/1.json
  def show
  end

  # GET /domains/new
  def new
    @domain = Domain.new
  end

  # GET /domains/1/edit
  def edit
  end

  # POST /domains
  # POST /domains.json
  def create
    @domain = Domain.new(domain_params)

    respond_to do |format|
      if @domain.save
        format.html { redirect_to @domain, notice: 'Domain was successfully created.' }
        format.json { render :show, status: :created, location: @domain }
      else
        logger.info "Domain unsaved: #{@domain.errors.messages.inspect}"
        format.html { render :new }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /domains/1
  # PATCH/PUT /domains/1.json
  def update
    respond_to do |format|
      if @domain.update(domain_params)
        format.html { redirect_to @domain, notice: 'Domain was successfully updated.' }
        format.json { render :show, status: :ok, location: @domain }
      else
        format.html { render :edit }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.json
  def destroy
    @domain.destroy
    respond_to do |format|
      format.html { redirect_to domains_url, notice: 'Domain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domain
      @domain = Domain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def domain_params
      params.require(:domain).permit(:name)
    end
end

app/controllers/txt_controller.rb
# frozen_string_literal: true

class TxtController < ApplicationController
  before_action :load_domain

  def set
    r = @domain.records.where(type: 'TXT').find_by_name(params[:domain])
    r = Record.new(type: 'TXT', domain: @domain, name: params[:domain], ttl: 300) if r.nil?

    content = params[:txtvalue]
    r.content = content

    result = r.save ? 'OK' : r.errors.map(&:to_s).join(':')
    render plain: result
  end

  def destroy
    r = @domain.records.where(type: 'TXT').find_by_name(params[:domain])
    if !r.nil?
      r.destroy
      render plain: 'OK - Record removed.'
    else
      render plain: 'Record not found.'
    end
  end

  def load_domain
    domain_parts = params[:domain].split('.')
    while !domain_parts.size.zero? do
        domain = domain_parts.join('.')
        @domain = Domain.find_by_name(domain)
        break if !@domain.nil?
        domain_parts.shift
    end

    if @domain.nil?
       render plain: 'Domain not found.'
       return false
    end

    puts "Domain found: #{@domain.id}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/domains/_form.html.erb
<%= form_for(@domain) do |form| %>
  <% if domain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

      <ul>
      <% domain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/domains/edit.html.erb
<h1>Editing Domain</h1>

<%= render 'form', domain: @domain %>

<%= link_to 'Show', @domain %> |
<%= link_to 'Back', domains_path %>

app/views/domains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Domains</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @domains.each do |domain| %>
      <tr>
        <td><%= domain.name %></td>
        <td><%= link_to 'Show', domain %></td>
        <td><%= link_to 'Edit', edit_domain_path(domain) %></td>
        <td><%= link_to 'Destroy', domain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Domain', new_domain_path %>

app/views/domains/new.html.erb
<h1>New Domain</h1>

<%= render 'form', domain: @domain %>

<%= link_to 'Back', domains_path %>

app/views/domains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @domain.name %>
</p>

<%= link_to 'Edit', edit_domain_path(@domain) %> |
<%= link_to 'Back', domains_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MinimumDnsApiR50</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>